name: deploy

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
        - 
            name: Checkout code
            uses: actions/checkout@v2

        - 
            name: Use Node.js
            uses: actions/setup-node@v2
            with:
                node-version: 18

        - 
            name: Configure AWS credentials
            uses: aws-actions/configure-aws-credentials@v4
            with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: us-east-1  

        - 
            name: Install sst ion
            run: curl -fsSL https://ion.sst.dev/install | bash

        - 
            name: Install dependencies
            run: cd ./client && npm install

        - 
            name: Deploy
            run: cd ./client && sst deploy --stage salad